import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Footer} from '/components/footer'
import { Links }from 'components/links'
import { Headline } from 'components/headline'
import { Main } from 'components/main'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main page="index">

      </Main>
      <Footer></Footer>
    </>
  )
}
