import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '/styles/Home.module.css'
import { Footer} from '/components/footer'
import { Links }from 'components/links'
import { Headline } from 'components/headline'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Headline page="Index Page!!" number ={1111} array={[1,2,3]}
        obj={{foo: "foo", bar: "bar"}}
        boolean={true}
        >

        </Headline>
        <div className={styles.center}>say oorchlson index</div>
      <Links></Links>
      </main>
      <Footer></Footer>
    </>
  )
}
